spring:
  application:
    name: Analytics

  threads:
    virtual:
      enabled: true

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: ${SERVICE_PORT}